steps:
  # Clone the repository
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/mmaazkhan/node-repo.git']
    dir: '/workspace'

  # Navigate to the repository directory
  - name: 'gcr.io/cloud-builders/bash'
    args:
      - '-c'
      - 'cd your-repo'

  # Install Node.js dependencies
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
    dir: '/workspace/your-repo'

  # Build the application (if needed)
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']
    dir: '/workspace/your-repo'

  # Upload files to a GCP Storage bucket (optional)
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', '-r', '.', 'gs://node-bucket-01/']
    dir: '/workspace/your-repo'

  # Deploy to VM instance
  - name: 'gcr.io/cloud-builders/ssh'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Deploying to VM..."
        gcloud compute ssh your-vm-instance --zone your-zone --command "cd /path/to/app && git pull && npm install && npm start"
