steps:
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/your-username/your-repo.git']
    dir: '/workspace'

  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
    dir: '/workspace/your-repo'

  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']
    dir: '/workspace/your-repo'

  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', '-r', '.', 'gs://node-bucket-01/']
    dir: '/workspace/your-repo'

  - name: 'gcr.io/cloud-builders/bash'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Deploying to VM..."
        gcloud compute ssh your-vm-instance --zone your-zone --command "cd /path/to/app && git pull && npm install && npm start"
